apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - release.yaml
  - namespace.yaml
configMapGenerator:
  - name: redis-values
    namespace: xinfra-cluster-config
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
